version: '3.5'
services: 
  app:
    image: tambourin/docker-excercise
    ports: 
      - 80:8000
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower