
version: 2.1
steps:
  - run: 
      command: >
        docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY
        registry.heroku.com
  - run:
      command: >
        heroku container:push web --app docker-excercise2
