version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t testapp .
      - run:
          name: Deploy to Heroku
          command: |         
            wget https://cli-assets.heroku.com/install.sh | sh
            docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
            docker tag testapp registry.heroku.com/docker-excercise2/web
            docker push registry.heroku.com/docker-excercise2/web
            
