orbs:
  docker: circleci/docker@1.2.1
version: 2.1
workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          deploy: false
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME