obs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: >
            echo "The command above installs Heroku, the command below deploys.
            What you do inbetween is up to you!"
version: 2.1
orbs:
  docker: circleci/docker@1.0.0
  heroku: circleci/heroku@1.0.1
workflows:
  deploy:
    jobs:
      - docker/publish:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 'latest'
  deploy-heroku:
    jobs:
      - deploy