version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'            
            wget https://cli-assets.heroku.com/install.sh | sh
            heroku -v
            ls -l
            docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
            heroku container:push web --app docker-excercise2
