version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            sudo apt-get update
            sudo apt-get install -g -y curl
            curl https://cli-assets.heroku.com/install.sh | sh
